server:
  port: 9999

spring:
  application:
    name: mq-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: yogovi.2020
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          #开启重试
          enabled: true
          #最大重试次数
          max-attempts: 3
          #重试间隔
          max-interval: 1000ms
